services:

    gearman:
      restart: always
      build: ./gearman
      ports:
        - "${GEARMAN_PORT}:4730"
      privileged: true
      environment:
        - GEARMAN_VERSION=${GEARMAN_VERSION}
        - GEARMAN_VERBOSE=${GEARMAN_VERBOSE}
        - GEARMAN_QUEUE_TYPE=${GEARMAN_QUEUE_TYPE}
        - GEARMAN_THREADS=${GEARMAN_THREADS}
        - GEARMAN_BACKLOG=${GEARMAN_BACKLOG}
        - GEARMAN_FILE_DESCRIPTORS=${GEARMAN_FILE_DESCRIPTORS}
        - GEARMAN_JOB_RETRIES=${GEARMAN_JOB_RETRIES}
        - GEARMAN_ROUND_ROBIN=${GEARMAN_ROUND_ROBIN}
        - GEARMAN_WORKER_WAKEUP=${GEARMAN_WORKER_WAKEUP}
        - GEARMAN_KEEPALIVE=${GEARMAN_KEEPALIVE}
        - GEARMAN_KEEPALIVE_IDLE=${GEARMAN_KEEPALIVE_IDLE}
        - GEARMAN_KEEPALIVE_INTERVAL=${GEARMAN_KEEPALIVE_INTERVAL}
        - GEARMAN_KEEPALIVE_COUNT=${GEARMAN_KEEPALIVE_COUNT}
        - GEARMAN_MYSQL_HOST=${GEARMAN_MYSQL_HOST}
        - GEARMAN_MYSQL_PORT=${GEARMAN_MYSQL_PORT}
        - GEARMAN_MYSQL_USER=${GEARMAN_MYSQL_USER}
        - GEARMAN_MYSQL_PASSWORD=${GEARMAN_MYSQL_PASSWORD}
        - GEARMAN_MYSQL_PASSWORD_FILE=${GEARMAN_MYSQL_PASSWORD_FILE}
        - GEARMAN_MYSQL_DB=${GEARMAN_MYSQL_DB}
        - GEARMAN_MYSQL_TABLE=${GEARMAN_MYSQL_TABLE}
      hostname: laradock-gearman
      depends_on:
        - php-fpm
      networks:
        - backend
