services:

    neo4j:
      restart: always
      ports:
          - '7401:7474'
          - '7402:7687'
      environment:
          - NEO4J_AUTH=none
      volumes:
          - ${DATA_PATH_HOST}/neo4j/data:/data
          - ${DATA_PATH_HOST}/neo4j/logs:/logs
      image: 'neo4j:latest'
      networks:
        - backend
