services:

    clickhouse:
      build:
        context: ./clickhouse
        args:
          - CLICKHOUSE_VERSION=${CLICKHOUSE_VERSION}
          - CLICKHOUSE_GOSU_VERSION=${CLICKHOUSE_GOSU_VERSION}
      environment:
        - CLICKHOUSE_USER=${CLICKHOUSE_USER}
        - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      volumes:
        - ${DATA_PATH_HOST}/clickhouse:/var/lib/clickhouse
        - ${CLICKHOUSE_CUSTOM_CONFIG}:/etc/clickhouse-server/config.xml
        - ${CLICKHOUSE_USERS_CUSTOM_CONFIG}:/etc/clickhouse-server/users.xml
        - ${CLICKHOUSE_HOST_LOG_PATH}:/var/log/clickhouse
        - ${CLICKHOUSE_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      links:
        - workspace
      ports:
        - "${CLICKHOUSE_HTTP_PORT}:8123"
        - "${CLICKHOUSE_CLIENT_PORT}:9000"
        - "${CLICKHOUSE_NATIVE_PORT}:9009"
      ulimits:
        nproc: 65535
        nofile:
          soft: 262144
          hard: 262144
      networks:
#        - frontend
        - backend
