services:

    pgvector:
      image: pgvector/pgvector:${PGVECTOR_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/pgvector:/var/lib/postgresql/data
        - ${PGVECTOR_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${PGVECTOR_PORT}:5432"
      environment:
        - POSTGRES_DB=${PGVECTOR_DB}
        - POSTGRES_USER=${PGVECTOR_USER}
        - POSTGRES_PASSWORD=${PGVECTOR_PASSWORD}
      networks:
        - backend
