# DO NOT CHANGE THIS FILE PLEASE.

github: [laradock, mahmoudz]
open_collective: laradock
ko_fi: laradock
issuehunt: laradock
custom: ['https://beerpay.io/laradock/laradock', 'https://www.paypal.me/mzmmzz']
