services:

    qdrant:
      image: qdrant/qdrant:${QDRANT_VERSION}
      volumes:
        - qdrant:/qdrant/storage
      ports:
        - "${QDRANT_HOST_PORT}:6333"
        - "${QDRANT_GRPC_PORT}:6334"
      networks:
        - frontend
        - backend
