version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ./:/var/www

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./laradock/workspace
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_SOAP=false
                - INSTALL_MONGO=false
                - INSTALL_NODE=true
                - INSTALL_YARN=true
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=true
                - INSTALL_WORKSPACE_SSH=false
                - INSTALL_WKHTMLTOPDF=true
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
                - TZ=Europe/Paris
        volumes_from:
            - applications
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        ports:
           - "2222:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./laradock/php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
                - INSTALL_WKHTMLTOPDF=true
                - INSTALL_AEROSPIKE_EXTENSION=false
                - CODEIGNITER=false
            dockerfile: Dockerfile-71
        volumes_from:
            - applications
        expose:
            - "9000"
        depends_on:
          - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG=serverName=laravel


### PHP Worker Container #####################################
    php-worker:
      build:
        context: ./php-worker
      volumes_from:
        - applications
      depends_on:
        - workspace

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./laradock/nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - applications
        volumes:
            - ./laradock/logs/nginx/:/var/log/nginx
            - ./laradock/nginx/sites/:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm

### PostgreSQL Container ####################################

    postgres:
        build: ./laradock/postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB: homestead
            - POSTGRES_USER: homestead
            - POSTGRES_PASSWORD: secret

### Redis Container #########################################

    redis:
        build: ./laradock/redis
        volumes:
            - redis:/data
        ports:
            - "6379:6379"

volumes:
    postgres:
        driver: "local"
    redis:
        driver: "local"
    sessions:
        driver: "local"
