version: "2"

services:

### Applications Code Container #############################

    applications:
      volumes:
        - ${APPLICATION}:/var/www:cached
        - ./.lpass-env:/var/www/api/.env
        - ./.lpass-env:/var/www/internal-october/.env
