networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  ollama:
    driver: ${VOLUMES_DRIVER}
  percona:
    driver: ${VOLUMES_DRIVER}
  localai:
    driver: ${VOLUMES_DRIVER}
  mssql:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  n8n:
    driver: ${VOLUMES_DRIVER}
  memcached:
    driver: ${VOLUMES_DRIVER}
  flowise:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  neo4j:
    driver: ${VOLUMES_DRIVER}
  qdrant:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  weaviate:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  minio:
    driver: ${VOLUMES_DRIVER}
  chroma:
    driver: ${VOLUMES_DRIVER}
  rethinkdb:
    driver: ${VOLUMES_DRIVER}
  arangodb:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}
  adminer:
    driver: ${VOLUMES_DRIVER}
  aerospike:
    driver: ${VOLUMES_DRIVER}
  surrealdb:
    driver: ${VOLUMES_DRIVER}
  caddy:
    driver: ${VOLUMES_DRIVER}
  meilisearch:
    driver: ${VOLUMES_DRIVER}
  typesense:
  pgvector:
    driver: ${VOLUMES_DRIVER}
  elasticsearch:
    driver: ${VOLUMES_DRIVER}
  mosquitto:
    driver: ${VOLUMES_DRIVER}
  confluence:
    driver: ${VOLUMES_DRIVER}
  sonarqube:
    driver: ${VOLUMES_DRIVER}
  cassandra:
    driver: ${VOLUMES_DRIVER}
  influxdb:
    driver: ${VOLUMES_DRIVER}
  graylog:
    driver: ${VOLUMES_DRIVER}
  prometheus:
    driver: ${VOLUMES_DRIVER}
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}

include:
  - path: adminer/compose.yml
    project_directory: .
  - path: aerospike/compose.yml
    project_directory: .
  - path: apache2/compose.yml
    project_directory: .
  - path: arangodb/compose.yml
    project_directory: .
  - path: aws-eb-cli/compose.yml
    project_directory: .
  - path: beanstalkd/compose.yml
    project_directory: .
  - path: beanstalkd-console/compose.yml
    project_directory: .
  - path: blackfire/compose.yml
    project_directory: .
  - path: caddy/compose.yml
    project_directory: .
  - path: cassandra/compose.yml
    project_directory: .
  - path: certbot/compose.yml
    project_directory: .
  - path: chroma/compose.yml
    project_directory: .
  - path: clickhouse/compose.yml
    project_directory: .
  - path: confluence/compose.yml
    project_directory: .
  - path: couchdb/compose.yml
    project_directory: .
  - path: dejavu/compose.yml
    project_directory: .
  - path: docker-in-docker/compose.yml
    project_directory: .
  - path: docker-registry/compose.yml
    project_directory: .
  - path: dragonfly/compose.yml
    project_directory: .
  - path: elasticsearch/compose.yml
    project_directory: .
  - path: flowise/compose.yml
    project_directory: .
  - path: frankenphp/compose.yml
    project_directory: .
  - path: gearman/compose.yml
    project_directory: .
  - path: gitlab/compose.yml
    project_directory: .
  - path: gitlab-runner/compose.yml
    project_directory: .
  - path: grafana/compose.yml
    project_directory: .
  - path: graylog/compose.yml
    project_directory: .
  - path: haproxy/compose.yml
    project_directory: .
  - path: ide-theia/compose.yml
    project_directory: .
  - path: influxdb/compose.yml
    project_directory: .
  - path: jenkins/compose.yml
    project_directory: .
  - path: kafka/compose.yml
    project_directory: .
  - path: kafka-manager/compose.yml
    project_directory: .
  - path: keycloak/compose.yml
    project_directory: .
  - path: kibana/compose.yml
    project_directory: .
  - path: laravel-echo-server/compose.yml
    project_directory: .
  - path: laravel-horizon/compose.yml
    project_directory: .
  - path: laravel-reverb/compose.yml
    project_directory: .
  - path: litellm/compose.yml
    project_directory: .
  - path: localai/compose.yml
    project_directory: .
  - path: logstash/compose.yml
    project_directory: .
  - path: mailcatcher/compose.yml
    project_directory: .
  - path: maildev/compose.yml
    project_directory: .
  - path: mailhog/compose.yml
    project_directory: .
  - path: mailpit/compose.yml
    project_directory: .
  - path: mailu/compose.yml
    project_directory: .
  - path: manticore/compose.yml
    project_directory: .
  - path: mariadb/compose.yml
    project_directory: .
  - path: meilisearch/compose.yml
    project_directory: .
  - path: memcached/compose.yml
    project_directory: .
  - path: mercure/compose.yml
    project_directory: .
  - path: metabase/compose.yml
    project_directory: .
  - path: minio/compose.yml
    project_directory: .
  - path: mongo/compose.yml
    project_directory: .
  - path: mongo-webui/compose.yml
    project_directory: .
  - path: mosquitto/compose.yml
    project_directory: .
  - path: mssql/compose.yml
    project_directory: .
  - path: mysql/compose.yml
    project_directory: .
  - path: n8n/compose.yml
    project_directory: .
  - path: nats/compose.yml
    project_directory: .
  - path: neo4j/compose.yml
    project_directory: .
  - path: netdata/compose.yml
    project_directory: .
  - path: nginx/compose.yml
    project_directory: .
  - path: ollama/compose.yml
    project_directory: .
  - path: onedev/compose.yml
    project_directory: .
  - path: openresty/compose.yml
    project_directory: .
  - path: opensearch/compose.yml
    project_directory: .
  - path: percona/compose.yml
    project_directory: .
  - path: pgadmin/compose.yml
    project_directory: .
  - path: pgbackups/compose.yml
    project_directory: .
  - path: pgvector/compose.yml
    project_directory: .
  - path: php-fpm/compose.yml
    project_directory: .
  - path: php-worker/compose.yml
    project_directory: .
  - path: phpmyadmin/compose.yml
    project_directory: .
  - path: portainer/compose.yml
    project_directory: .
  - path: postgres/compose.yml
    project_directory: .
  - path: postgres-postgis/compose.yml
    project_directory: .
  - path: prometheus/compose.yml
    project_directory: .
  - path: qdrant/compose.yml
    project_directory: .
  - path: rabbitmq/compose.yml
    project_directory: .
  - path: redis/compose.yml
    project_directory: .
  - path: redis-cluster/compose.yml
    project_directory: .
  - path: redis-webui/compose.yml
    project_directory: .
  - path: rethinkdb/compose.yml
    project_directory: .
  - path: roadrunner/compose.yml
    project_directory: .
  - path: selenium/compose.yml
    project_directory: .
  - path: soketi/compose.yml
    project_directory: .
  - path: solr/compose.yml
    project_directory: .
  - path: sonarqube/compose.yml
    project_directory: .
  - path: sqs/compose.yml
    project_directory: .
  - path: ssdb/compose.yml
    project_directory: .
  - path: surrealdb/compose.yml
    project_directory: .
  - path: swagger-editor/compose.yml
    project_directory: .
  - path: swagger-ui/compose.yml
    project_directory: .
  - path: tarantool/compose.yml
    project_directory: .
  - path: tarantool-admin/compose.yml
    project_directory: .
  - path: thumbor/compose.yml
    project_directory: .
  - path: tomcat/compose.yml
    project_directory: .
  - path: traefik/compose.yml
    project_directory: .
  - path: typesense/compose.yml
    project_directory: .
  - path: valkey/compose.yml
    project_directory: .
  - path: varnish/compose.yml
    project_directory: .
  - path: weaviate/compose.yml
    project_directory: .
  - path: workspace/compose.yml
    project_directory: .
  - path: zookeeper/compose.yml
    project_directory: .
