version: '2'

services:

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_NODE=true
                - NODE_VERSION=stable
                - COMPOSER_GLOBAL_INSTALL=true
                - INSTALL_WORKSPACE_SSH=true
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        ports:
           - "23:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_ZIP_ARCHIVE=true
                - INSTALL_MEMCACHED=true
                - INSTALL_OPCACHE=true
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        ports:
            - "24:22"
            - "29000:9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG=serverName=lara.dev
        tty: true

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "20080:80"
            - "20443:443"
        links:
            - php-fpm

### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes_from:
            - volumes_data
        ports:
            - "25432:5432"
        environment:
            POSTGRES_DB: lara
            POSTGRES_USER: dbuser
            POSTGRES_PASSWORD: password

### Redis Container #########################################

    redis:
        build: ./redis
        volumes_from:
            - volumes_data
        ports:
            - "26379:6379"

### Memcached Container #####################################

    memcached:
        build: ./memcached
        volumes_from:
            - volumes_data
        ports:
            - "21211:11211"
        links:
            - php-fpm

### Laravel Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ../:/var/www/laravel
            # Demonstration of how to mount multiple sites
            # - ../../site_a/:/var/www/site_a
            # - ../../site_b/:/var/www/site_b

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/sessions:/sessions

### Add more Containers below ###############################
