# PHP + NGINX Container #----------------------------------
php-nginx:
  image: eric28/php56nginx:latest
  container_name: php-nginx
  ports:
    - "80:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - ../:/var/www
    - ./logs/nginx:/var/log/nginx
    - ./settings/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
  links:
    - mysql
   # - redis
  privileged: true
  extra_hosts:
     - "ocoval.sigoincidencias.local:127.0.0.1"

# MySQL Container #----------------------------------------
mysql:
  image: mysql:latest
  container_name: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_DATABASE: ocoval_incidencias
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  privileged: true

# Redis Container #----------------------------------------
#redis:
#  image: laradock/redis:0.1.0
#  container_name: redis
#  ports:
#    - "6379:6379"
#  volumes_from:
#    - data
#  volumes:
#    - ./logs/redis:/var/log/redis
#  restart: always
#  privileged: true

# Data Volume Container #----------------------------------
data:
  image: laradock/data:0.1.0
  container_name: data
  volumes:
    - /var/lib/mysql
#    - /var/lib/redis

# Beanstalkd Container #-----------------------------------
# beanstalkd:
#   image: laradock/beanstalkd:0.1.0
#   container_name: beanstalkd
#   ports:
#     - "11300:11300"
#   privileged: true

#----------------------------------------------------------
