#!/bin/bash

#####################################################
# This is a starter for Laradock
# 
# See details on https://github.com/laradock/laradock
# Author: Dmitry Pupinin
# Version: 0.1.0
#####################################################

if [ -d "${PWD}/.laradock" ];
then
    script_dir="${PWD}/.laradock"
else
    if [ -d "${PWD}/../.laradock" ];
    then
        script_dir="${PWD}/../.laradock"
    else
        echo "Warning! Laradock not found for this project."
        exit 1
    fi
fi

$script_dir/ldk-cli $*
