services:

    confluence:
      container_name: Confluence
      image: atlassian/confluence-server:${CONFLUENCE_VERSION}
      restart: always
      ports:
        - "${CONFLUENCE_HOST_HTTP_PORT}:8090"
      networks:
        - frontend
        - backend
      depends_on:
        - postgres
      volumes:
        - ${DATA_PATH_HOST}/Confluence:/var/atlassian/application-data
