services:

    n8n:
      image: n8nio/n8n:${N8N_VERSION}
      volumes:
        - n8n:/home/node/.n8n
      ports:
        - "${N8N_HOST_PORT}:5678"
      environment:
        - N8N_SECURE_COOKIE=false
      networks:
        - frontend
        - backend
