services:

    onedev:
      image: 1dev/server
      ports:
        - "${ONEDEV_HTTP_PORT}:6610"
        - "${ONEDEV_SSH_PORT}:6611"
      volumes:
        - ${DATA_PATH_HOST}/onedev:/opt/onedev
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - frontend
        - backend
      restart: always
