FROM python

LABEL maintainer="ahkui <ahkui@outlook.com>"

USER root

RUN pip --no-cache-dir install ipyparallel

RUN ipython profile create --parallel --profile=default

COPY ipcontroller-client.json /root/.ipython/profile_default/security/ipcontroller-client.json
COPY ipcontroller-engine.json /root/.ipython/profile_default/security/ipcontroller-engine.json

CMD ['sh','-c','ipcluster engines']
