services:

    sqs:
      restart: always
      build: ./sqs
      ports:
        - "${SQS_NODE_HOST_PORT}:9324"
        - "${SQS_MANAGEMENT_HTTP_HOST_PORT}:9325"
      privileged: true
      hostname: laradock-sqs
      volumes:
        - ${DATA_PATH_HOST}/sqs:/opt/custom
      networks:
        - frontend
        - backend
