FROM konradkleine/docker-registry-frontend:v2

LABEL maintainer="ahkui <ahkui@outlook.com>"

ENV ENV_DOCKER_REGISTRY_HOST=${DOCKER_WEBUI_REGISTRY_HOST}
ENV ENV_DOCKER_REGISTRY_PORT=${DOCKER_WEBUI_REGISTRY_PORT}
  