services:

    aws:
      restart: always
      build:
        context: ./aws-eb-cli
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      depends_on:
        - workspace
      tty: true
