FROM fenglc/pgadmin4:alpine

LABEL maintainer="Huadong Zuo <admin@zuohuadong.cn>"

# user: pgadmin4@pgadmin.org
# password: admin
# pg_dump & postgresql all in  "/usr/bin"
# backup in "/var/lib/pgadmin/storage/pgadmin4"

EXPOSE 5050
