services:

    gitlab:
      build:
        context: ./gitlab
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url '${GITLAB_DOMAIN_NAME}'
          redis['enable'] = false
          nginx['listen_https'] = false
          nginx['listen_port'] = 80
          nginx['custom_gitlab_server_config'] = "set_real_ip_from 172.0.0.0/8;\nreal_ip_header X-Real-IP;\nreal_ip_recursive on;"
          postgresql['enable'] = false
          gitlab_rails['trusted_proxies'] = ['caddy','nginx','apache2']
          gitlab_rails['redis_host'] = 'redis'
          gitlab_rails['redis_database'] = 8
          gitlab_rails['db_host'] = '${GITLAB_POSTGRES_HOST}'
          gitlab_rails['db_username'] = '${GITLAB_POSTGRES_USER}'
          gitlab_rails['db_password'] = '${GITLAB_POSTGRES_PASSWORD}'
          gitlab_rails['db_database'] = '${GITLAB_POSTGRES_DB}'
          gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
          gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_HOST_SSH_PORT}
      volumes:
        - ${DATA_PATH_HOST}/gitlab/config:/etc/gitlab
        - ${DATA_PATH_HOST}/gitlab/data:/var/opt/gitlab
        - ${GITLAB_HOST_LOG_PATH}:/var/log/gitlab
      ports:
        - "${GITLAB_HOST_HTTP_PORT}:80"
        - "${GITLAB_HOST_HTTPS_PORT}:443"
        - "${GITLAB_HOST_SSH_PORT}:22"
      networks:
        - backend
      depends_on:
        - redis
        - postgres
