services:

    ide-theia:
      build:
        context: ./ide-theia
      volumes:
        - ${APP_CODE_PATH_HOST}:/home/project
      ports:
        - "${IDE_THEIA_PORT}:3000"
      networks:
        - backend
