FROM adminer:latest

MAINTAINER Patrick Artounian <partounian@gmail.com>

# Add volume for sessions to allow session persistence
VOLUME /sessions

# We expose Adminer on port 8080 (Adminer's default)
EXPOSE 8080
