services:

    arangodb:
      image: arangodb:${ARANGODB_VERSION}
      environment:
        - ARANGO_ROOT_PASSWORD=${ARANGODB_ROOT_PASSWORD}
      volumes:
        - arangodb:/var/lib/arangodb3
      ports:
        - "${ARANGODB_PORT}:8529"
      networks:
        - frontend
        - backend
