services:

    pgbackups:
      image: prodrigestivill/postgres-backup-local
      restart: always
      volumes:
        - ../backup:/backups
      links:
        - postgres
      environment:
        - POSTGRES_HOST={POSTGRES_HOST}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend
