services:

    couchdb:
      build:
        context: ./couchdb
      volumes:
        - ${DATA_PATH_HOST}/couchdb/data:/opt/couchdb/data
      ports:
        - "${COUCHDB_PORT}:5984"
      networks:
        - backend
