services:

    maildev:
      restart: always
      build: ./maildev
      ports:
        - "${MAILDEV_HTTP_PORT}:1080"
        - "${MAILDEV_SMTP_PORT}:25"
      networks:
        - frontend
        - backend
