#!/bin/sh

cd "${BASH_SOURCE%/*}" || exit
cd ../

echo "==> This may build a container please wait until the build finished to enter you password!"
echo "Please enter your @kiron.ngo username usualle first_name.last_name followed by [ENTER]:"
read username

if [[ -z  $username  ]]; then
  echo "your username is empty, try again."
  read username
fi

docker-compose up -d lpass
docker-compose exec lpass lpass login ${username}@kiron.ngo
docker-compose exec lpass lpass show --notes 1831093418396261581 > .lpass-env
docker-compose exec lpass lpass show --notes 6712496210517417879 >> .env
echo "DB_TRANSFER_ENVNAME=${username}" >> .lpass-env
docker-compose stop lpass
