#!/bin/sh

set -e

cd "$(dirname "$0")/.."

cp base-env .env
touch .lpass-env

read -p "Do you want to load secrets from lastpass? (y/n)" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    script/load-lpass
fi
