#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

ETC_HOSTS_FILE="/etc/hosts"

domains=("internal" "curriculum" "api" "campus-frontend")

set -e

cd "$(dirname "$0")/.."

git pull
git submodule update --remote

script/setenv

echo "==> Add Domains to ${ETC_HOSTS_FILE} and trust self signed certificates."
for domain in ${domains[@]}
do
    if grep -Fxq "127.0.0.1 ${domain}.app" $ETC_HOSTS_FILE
    then
        echo "${domain}.app hosts file OK"
    else
        echo "127.0.0.1 ${domain}.app" | sudo tee -a $ETC_HOSTS_FILE
        echo "Added ${domain}.app to hosts"
    fi
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Adding cert for $domain to keychain"
        sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain nginx/certs/$domain.crt
    fi
done

echo "==> Building images"
services="`cat script/services.lst`"
docker-compose build --pull $services

script/bootstrap

echo "==> App is now ready to go!"
echo "==> Run script/server to start the dev env."
echo "==> Run script/update to update the dev env."
