#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

echo "==> Fetching updates form git..."
git pull
repos="`cat script/.repos.lst`"
for repo in ${repos[@]}
do
    cd ${repo}
    git checkout master
    git pull
    cd ..
done

script/setenv

script/bootstrap
