services:

    graylog:
      restart: always
      build: ./graylog
      environment:
        - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD}
        - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_SHA256_PASSWORD}
        - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:${GRAYLOG_PORT}/
      links:
        - mongo
        - elasticsearch
      depends_on:
        - mongo
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - ${GRAYLOG_PORT}:9000
        # Syslog TCP
        - ${GRAYLOG_SYSLOG_TCP_PORT}:514
        # Syslog UDP
        - ${GRAYLOG_SYSLOG_UDP_PORT}:514/udp
        # GELF TCP
        - ${GRAYLOG_GELF_TCP_PORT}:12201
        # GELF UDP
        - ${GRAYLOG_GELF_UDP_PORT}:12201/udp
      user: graylog
      volumes:
        - ${DATA_PATH_HOST}/graylog:/usr/share/graylog/data
      networks:
        - backend
