services:

    soketi:
      build:
        context: ./soketi
        args:
          - NODE_VERSION=${SOKETI_NODE_VERSION}
          - BASE_IMAGE_TAG_PREFIX=${SOKETI_BASE_IMAGE_TAG_PREFIX}
      volumes:
        - ./soketi/config.json:/app/bin/config.json:ro
      ports:
        - "${SOKETI_PORT}:6001"
        - "${SOKETI_METRICS_SERVER_PORT}:9601"
      networks:
        - frontend
        - backend
