#!/usr/bin/with-contenv sh

options="-config /etc/consul-template/conf-services.d -consul-addr ${CONSUL_AGENT}:${CONSUL_PORT}"

if [ ! -z "${CONSUL_TLS}" ] && [ "${CONSUL_TLS}" -eq 1 ]; then
    options="${options} -consul-ssl"

    if [ ! -z "${CONSUL_TLSCAFILE}" ]; then
        options="${options} -consul-ssl-ca-cert ${CONSUL_TLSCAFILE}"
    fi

    if [ ! -z "${CONSUL_TLSCERTFILE}" ]; then
        options="${options} -consul-ssl-cert ${CONSUL_TLSCERTFILE}"
    fi

    if [ ! -z "${CONSUL_TLSKEYFILE}" ]; then
        options="${options} -consul-ssl-key ${CONSUL_TLSKEYFILE}"
    fi

    if [ ! -z "${CONSUL_TLSSERVERNAME}" ]; then
        options="${options} -consul-ssl-server-name ${CONSUL_TLSSERVERNAME}"
    fi

    if [ ! -z "${CONSUL_TLSVERIFY}" ] && [ "${CONSUL_TLSVERIFY}" -eq 1 ]; then
        options="${options} -consul-ssl-verify"
    fi
fi

if [ ! -z "${CONSUL_TOKEN}" ]; then
    options="${options} -consul-token ${CONSUL_TOKEN}"
fi

options="${options} -kill-signal SIGTERM"

if [ ! -z "${CONSULTEMPLATE_OPTIONS}" ]; then
    options="${options} ${CONSULTEMPLATE_OPTIONS}"
fi

exec /bin/consul-template ${options}
