#!/usr/bin/with-contenv sh

if [ ! -z "${CONSUL_AGENT}" ]; then
    echo "==> Registering container"

    /etc/cont-consul/register || (
        echo "Failed to register container, aborting" >&2 && exit 1
    )
fi
