import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Manual sidebar. Long single-page docs (Intro, Getting Started) expose their
 * sections as in-page anchor links so the sidebar stays useful without splitting
 * content across pages (easier to search / copy / feed to an AI agent).
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Introduction",
      link: { type: "doc", id: "Intro" },
      collapsible: true,
      collapsed: false,
      items: [
        { type: "link", label: "Features", href: "/docs/Intro#features" },
        { type: "link", label: "How Laradock Compares", href: "/docs/Intro#laradock-alternatives" },
        { type: "link", label: "Supported Services", href: "/docs/Intro#supported-services" },
        { type: "link", label: "Quick Start", href: "/docs/Intro#quick-start" },
        { type: "link", label: "Awesome People", href: "/docs/Intro#awesome-people" },
        { type: "link", label: "Sponsors", href: "/docs/Intro#sponsors" },
        { type: "link", label: "License", href: "/docs/Intro#license" },
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      link: { type: "doc", id: "getting-started" },
      collapsible: true,
      collapsed: true,
      items: [
        { type: "link", label: "Requirements", href: "/docs/getting-started#requirements" },
        { type: "link", label: "Installation", href: "/docs/getting-started#installation" },
        { type: "link", label: "Usage", href: "/docs/getting-started#usage" },
      ],
    },
    "cli",
    {
      type: "category",
      label: "Usage",
      link: { type: "doc", id: "usage" },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Containers",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "List running containers", href: "/docs/usage#list-running-containers" },
            { type: "link", label: "Enter a container", href: "/docs/usage#enter-a-container" },
            { type: "link", label: "Build or rebuild", href: "/docs/usage#build-or-rebuild-containers" },
            { type: "link", label: "View log files", href: "/docs/usage#view-logs" },
          ],
        },
        {
          type: "category",
          label: "PHP",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "Install extensions", href: "/docs/usage#install-php-extensions" },
            { type: "link", label: "Change PHP-FPM version", href: "/docs/usage#change-the-php-fpm-version" },
            { type: "link", label: "Install xDebug", href: "/docs/usage#install-xdebug" },
            { type: "link", label: "Start or stop xDebug", href: "/docs/usage#start-or-stop-xdebug" },
          ],
        },
        {
          type: "category",
          label: "Laravel",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "Install Laravel", href: "/docs/usage#install-laravel" },
            { type: "link", label: "Run Artisan commands", href: "/docs/usage#run-artisan-commands" },
            { type: "link", label: "Queue worker", href: "/docs/usage#run-the-queue-worker" },
            { type: "link", label: "Scheduler", href: "/docs/usage#run-the-scheduler" },
          ],
        },
        {
          type: "category",
          label: "Use a Service",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "Redis", href: "/docs/usage#redis" },
            { type: "link", label: "PhpMyAdmin", href: "/docs/usage#phpmyadmin" },
            { type: "link", label: "ElasticSearch", href: "/docs/usage#elasticsearch" },
            { type: "link", label: "Grafana", href: "/docs/usage#grafana" },
          ],
        },
        { type: "link", label: "Prepare for Production", href: "/docs/usage#prepare-laradock-for-production" },
      ],
    },
    {
      type: "category",
      label: "Supported PHP Projects",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Frameworks",
          collapsible: true,
          collapsed: true,
          items: [
            "supported-php-projects/frameworks/laravel-on-docker",
            "supported-php-projects/frameworks/symfony-on-docker",
            "supported-php-projects/frameworks/codeigniter-on-docker",
            "supported-php-projects/frameworks/yii-on-docker",
            "supported-php-projects/frameworks/laminas-on-docker",
            "supported-php-projects/frameworks/cakephp-on-docker",
            "supported-php-projects/frameworks/phalcon-on-docker",
            "supported-php-projects/frameworks/slim-on-docker",
            "supported-php-projects/frameworks/lumen-on-docker",
            "supported-php-projects/frameworks/fuelphp-on-docker",
            "supported-php-projects/frameworks/spiral-on-docker",
            "supported-php-projects/frameworks/hyperf-on-docker",
            "supported-php-projects/frameworks/api-platform-on-docker",
            "supported-php-projects/frameworks/mezzio-on-docker",
            "supported-php-projects/frameworks/flight-on-docker",
            "supported-php-projects/frameworks/fat-free-framework-on-docker",
            "supported-php-projects/frameworks/thinkphp-on-docker",
            "supported-php-projects/frameworks/silex-on-docker",
            "supported-php-projects/frameworks/swoole-on-docker",
            "supported-php-projects/frameworks/workerman-on-docker",
            "supported-php-projects/frameworks/ubiquity-on-docker",
            "supported-php-projects/frameworks/silverstripe-on-docker",
            "supported-php-projects/frameworks/nette-on-docker",
            "supported-php-projects/frameworks/leaf-php-on-docker",
          ],
        },
        {
          type: "category",
          label: "CMS",
          collapsible: true,
          collapsed: true,
          items: [
            "supported-php-projects/cms/wordpress-on-docker",
            "supported-php-projects/cms/drupal-on-docker",
            "supported-php-projects/cms/joomla-on-docker",
            "supported-php-projects/cms/october-cms-on-docker",
            "supported-php-projects/cms/statamic-on-docker",
            "supported-php-projects/cms/craft-cms-on-docker",
            "supported-php-projects/cms/typo3-on-docker",
            "supported-php-projects/cms/concrete-cms-on-docker",
            "supported-php-projects/cms/grav-on-docker",
            "supported-php-projects/cms/backdrop-cms-on-docker",
            "supported-php-projects/cms/htmly-on-docker",
            "supported-php-projects/cms/kirby-on-docker",
            "supported-php-projects/cms/processwire-on-docker",
            "supported-php-projects/cms/pico-on-docker",
            "supported-php-projects/cms/bolt-cms-on-docker",
            "supported-php-projects/cms/contao-on-docker",
            "supported-php-projects/cms/b2evolution-on-docker",
            "supported-php-projects/cms/serendipity-on-docker",
            "supported-php-projects/cms/nucleus-cms-on-docker",
            "supported-php-projects/cms/e107-on-docker",
            "supported-php-projects/cms/pligg-on-docker",
            "supported-php-projects/cms/sulu-cms-on-docker",
            "supported-php-projects/cms/pimcore-on-docker",
            "supported-php-projects/cms/winter-cms-on-docker",
            "supported-php-projects/cms/neos-cms-on-docker",
            "supported-php-projects/cms/textpattern-on-docker",
            "supported-php-projects/cms/expressionengine-on-docker",
          ],
        },
        {
          type: "category",
          label: "E-commerce",
          collapsible: true,
          collapsed: true,
          items: [
            "supported-php-projects/e-commerce/magento-on-docker",
            "supported-php-projects/e-commerce/woocommerce-on-docker",
            "supported-php-projects/e-commerce/prestashop-on-docker",
            "supported-php-projects/e-commerce/opencart-on-docker",
            "supported-php-projects/e-commerce/sylius-on-docker",
            "supported-php-projects/e-commerce/bagisto-on-docker",
            "supported-php-projects/e-commerce/aimeos-on-docker",
            "supported-php-projects/e-commerce/avored-on-docker",
            "supported-php-projects/e-commerce/orocommerce-on-docker",
            "supported-php-projects/e-commerce/zen-cart-on-docker",
            "supported-php-projects/e-commerce/oscommerce-on-docker",
            "supported-php-projects/e-commerce/abantecart-on-docker",
            "supported-php-projects/e-commerce/cubecart-on-docker",
            "supported-php-projects/e-commerce/shopware-on-docker",
            "supported-php-projects/e-commerce/litecart-on-docker",
            "supported-php-projects/e-commerce/openmage-on-docker",
          ],
        },
        {
          type: "category",
          label: "Apps",
          collapsible: true,
          collapsed: true,
          items: [
            "supported-php-projects/apps/moodle-on-docker",
            "supported-php-projects/apps/mediawiki-on-docker",
            "supported-php-projects/apps/phpbb-on-docker",
            "supported-php-projects/apps/matomo-on-docker",
            "supported-php-projects/apps/mybb-on-docker",
            "supported-php-projects/apps/fluxbb-on-docker",
            "supported-php-projects/apps/punbb-on-docker",
            "supported-php-projects/apps/flarum-on-docker",
            "supported-php-projects/apps/bbpress-on-docker",
            "supported-php-projects/apps/smf-on-docker",
            "supported-php-projects/apps/dokuwiki-on-docker",
            "supported-php-projects/apps/bookstack-on-docker",
            "supported-php-projects/apps/roundcube-on-docker",
            "supported-php-projects/apps/phpmyadmin-on-docker",
            "supported-php-projects/apps/adminer-on-docker",
            "supported-php-projects/apps/suitecrm-on-docker",
            "supported-php-projects/apps/espocrm-on-docker",
            "supported-php-projects/apps/vtiger-on-docker",
            "supported-php-projects/apps/dolibarr-on-docker",
            "supported-php-projects/apps/aureus-erp-on-docker",
            "supported-php-projects/apps/weberp-on-docker",
            "supported-php-projects/apps/frontaccounting-on-docker",
            "supported-php-projects/apps/kanboard-on-docker",
            "supported-php-projects/apps/firefly-iii-on-docker",
            "supported-php-projects/apps/invoice-ninja-on-docker",
            "supported-php-projects/apps/x2crm-on-docker",
            "supported-php-projects/apps/nextcloud-on-docker",
            "supported-php-projects/apps/owncloud-on-docker",
            "supported-php-projects/apps/pydio-on-docker",
            "supported-php-projects/apps/mautic-on-docker",
            "supported-php-projects/apps/crater-on-docker",
            "supported-php-projects/apps/akaunting-on-docker",
            "supported-php-projects/apps/monica-crm-on-docker",
            "supported-php-projects/apps/leantime-on-docker",
            "supported-php-projects/apps/cachet-on-docker",
            "supported-php-projects/apps/php-server-monitor-on-docker",
            "supported-php-projects/apps/yourls-on-docker",
            "supported-php-projects/apps/linkace-on-docker",
            "supported-php-projects/apps/koel-on-docker",
            "supported-php-projects/apps/azuracast-on-docker",
            "supported-php-projects/apps/lychee-on-docker",
            "supported-php-projects/apps/vanilla-forums-on-docker",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Laradock vs Others",
      link: { type: "doc", id: "laradock-vs-others/comparison" },
      collapsible: true,
      collapsed: true,
      items: [
        "laradock-vs-others/laradock-vs-ddev",
        "laradock-vs-others/laradock-vs-laravel-sail",
        "laradock-vs-others/laradock-vs-laravel-herd",
        "laradock-vs-others/laradock-vs-valet",
        "laradock-vs-others/laradock-vs-xampp",
        "laradock-vs-others/laradock-vs-laragon",
        "laradock-vs-others/laradock-vs-local-wp",
        "laradock-vs-others/laradock-vs-homestead",
        "laradock-vs-others/laradock-vs-lando",
        "laradock-vs-others/laradock-vs-devcontainers",
        "laradock-vs-others/laradock-vs-docker-compose",
        "laradock-vs-others/laradock-vs-manual-install",
      ],
    },
    "help",
    "community",
    "related-projects",
    "contributing",
  ],
};

export default sidebars;
