import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Manual sidebar. Long single-page docs (Intro, Getting Started) expose their
 * sections as in-page anchor links so the sidebar stays useful without splitting
 * content across pages (easier to search / copy / feed to an AI agent).
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Introduction",
      link: { type: "doc", id: "Intro" },
      collapsible: true,
      collapsed: false,
      items: [
        { type: "link", label: "Features", href: "/docs/Intro#features" },
        { type: "link", label: "How Laradock Compares", href: "/docs/Intro#laradock-alternatives" },
        { type: "link", label: "Supported Services", href: "/docs/Intro#supported-services" },
        { type: "link", label: "Quick Start", href: "/docs/Intro#quick-start" },
        { type: "link", label: "Awesome People", href: "/docs/Intro#awesome-people" },
        { type: "link", label: "Sponsors", href: "/docs/Intro#sponsors" },
        { type: "link", label: "License", href: "/docs/Intro#license" },
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      link: { type: "doc", id: "getting-started" },
      collapsible: true,
      collapsed: true,
      items: [
        { type: "link", label: "Requirements", href: "/docs/getting-started#requirements" },
        { type: "link", label: "Installation", href: "/docs/getting-started#installation" },
        { type: "link", label: "Usage", href: "/docs/getting-started#usage" },
      ],
    },
    { type: "doc", id: "cli", label: "CLI Reference" },
    {
      type: "category",
      label: "Supported PHP Projects",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Frameworks",
          collapsible: true,
          collapsed: true,
          items: [
            "supported-php-projects/frameworks/laravel-on-docker",
            "supported-php-projects/frameworks/symfony-on-docker",
            "supported-php-projects/frameworks/codeigniter-on-docker",
            "supported-php-projects/frameworks/yii-on-docker",
            "supported-php-projects/frameworks/laminas-on-docker",
            "supported-php-projects/frameworks/cakephp-on-docker",
            "supported-php-projects/frameworks/phalcon-on-docker",
            "supported-php-projects/frameworks/slim-on-docker",
            "supported-php-projects/frameworks/lumen-on-docker",
            "supported-php-projects/frameworks/fuelphp-on-docker",
            "supported-php-projects/frameworks/spiral-on-docker",
            "supported-php-projects/frameworks/hyperf-on-docker",
            "supported-php-projects/frameworks/api-platform-on-docker",
            "supported-php-projects/frameworks/mezzio-on-docker",
            "supported-php-projects/frameworks/flight-on-docker",
            "supported-php-projects/frameworks/fat-free-framework-on-docker",
            "supported-php-projects/frameworks/thinkphp-on-docker",
            "supported-php-projects/frameworks/silex-on-docker",
            "supported-php-projects/frameworks/swoole-on-docker",
            "supported-php-projects/frameworks/workerman-on-docker",
            "supported-php-projects/frameworks/ubiquity-on-docker",
            "supported-php-projects/frameworks/silverstripe-on-docker",
            "supported-php-projects/frameworks/nette-on-docker",
            "supported-php-projects/frameworks/leaf-php-on-docker",
          ],
        },
        {
          type: "category",
          label: "CMS",
          collapsible: true,
          collapsed: true,
          items: [
            "supported-php-projects/cms/wordpress-on-docker",
            "supported-php-projects/cms/drupal-on-docker",
            "supported-php-projects/cms/joomla-on-docker",
            "supported-php-projects/cms/october-cms-on-docker",
            "supported-php-projects/cms/statamic-on-docker",
            "supported-php-projects/cms/craft-cms-on-docker",
            "supported-php-projects/cms/typo3-on-docker",
            "supported-php-projects/cms/concrete-cms-on-docker",
            "supported-php-projects/cms/grav-on-docker",
            "supported-php-projects/cms/backdrop-cms-on-docker",
            "supported-php-projects/cms/htmly-on-docker",
            "supported-php-projects/cms/kirby-on-docker",
            "supported-php-projects/cms/processwire-on-docker",
            "supported-php-projects/cms/pico-on-docker",
            "supported-php-projects/cms/bolt-cms-on-docker",
            "supported-php-projects/cms/contao-on-docker",
            "supported-php-projects/cms/b2evolution-on-docker",
            "supported-php-projects/cms/serendipity-on-docker",
            "supported-php-projects/cms/nucleus-cms-on-docker",
            "supported-php-projects/cms/e107-on-docker",
            "supported-php-projects/cms/pligg-on-docker",
            "supported-php-projects/cms/sulu-cms-on-docker",
            "supported-php-projects/cms/pimcore-on-docker",
            "supported-php-projects/cms/winter-cms-on-docker",
            "supported-php-projects/cms/neos-cms-on-docker",
            "supported-php-projects/cms/textpattern-on-docker",
            "supported-php-projects/cms/expressionengine-on-docker",
          ],
        },
        {
          type: "category",
          label: "E-commerce",
          collapsible: true,
          collapsed: true,
          items: [
            "supported-php-projects/e-commerce/magento-on-docker",
            "supported-php-projects/e-commerce/woocommerce-on-docker",
            "supported-php-projects/e-commerce/prestashop-on-docker",
            "supported-php-projects/e-commerce/opencart-on-docker",
            "supported-php-projects/e-commerce/sylius-on-docker",
            "supported-php-projects/e-commerce/bagisto-on-docker",
            "supported-php-projects/e-commerce/aimeos-on-docker",
            "supported-php-projects/e-commerce/avored-on-docker",
            "supported-php-projects/e-commerce/orocommerce-on-docker",
            "supported-php-projects/e-commerce/zen-cart-on-docker",
            "supported-php-projects/e-commerce/oscommerce-on-docker",
            "supported-php-projects/e-commerce/abantecart-on-docker",
            "supported-php-projects/e-commerce/cubecart-on-docker",
            "supported-php-projects/e-commerce/shopware-on-docker",
            "supported-php-projects/e-commerce/litecart-on-docker",
            "supported-php-projects/e-commerce/openmage-on-docker",
          ],
        },
        {
          type: "category",
          label: "Apps",
          collapsible: true,
          collapsed: true,
          items: [
            "supported-php-projects/apps/moodle-on-docker",
            "supported-php-projects/apps/mediawiki-on-docker",
            "supported-php-projects/apps/phpbb-on-docker",
            "supported-php-projects/apps/matomo-on-docker",
            "supported-php-projects/apps/mybb-on-docker",
            "supported-php-projects/apps/fluxbb-on-docker",
            "supported-php-projects/apps/punbb-on-docker",
            "supported-php-projects/apps/flarum-on-docker",
            "supported-php-projects/apps/bbpress-on-docker",
            "supported-php-projects/apps/smf-on-docker",
            "supported-php-projects/apps/dokuwiki-on-docker",
            "supported-php-projects/apps/bookstack-on-docker",
            "supported-php-projects/apps/roundcube-on-docker",
            "supported-php-projects/apps/phpmyadmin-on-docker",
            "supported-php-projects/apps/adminer-on-docker",
            "supported-php-projects/apps/suitecrm-on-docker",
            "supported-php-projects/apps/espocrm-on-docker",
            "supported-php-projects/apps/vtiger-on-docker",
            "supported-php-projects/apps/dolibarr-on-docker",
            "supported-php-projects/apps/aureus-erp-on-docker",
            "supported-php-projects/apps/weberp-on-docker",
            "supported-php-projects/apps/frontaccounting-on-docker",
            "supported-php-projects/apps/kanboard-on-docker",
            "supported-php-projects/apps/firefly-iii-on-docker",
            "supported-php-projects/apps/invoice-ninja-on-docker",
            "supported-php-projects/apps/x2crm-on-docker",
            "supported-php-projects/apps/nextcloud-on-docker",
            "supported-php-projects/apps/owncloud-on-docker",
            "supported-php-projects/apps/pydio-on-docker",
            "supported-php-projects/apps/mautic-on-docker",
            "supported-php-projects/apps/crater-on-docker",
            "supported-php-projects/apps/akaunting-on-docker",
            "supported-php-projects/apps/monica-crm-on-docker",
            "supported-php-projects/apps/leantime-on-docker",
            "supported-php-projects/apps/cachet-on-docker",
            "supported-php-projects/apps/php-server-monitor-on-docker",
            "supported-php-projects/apps/yourls-on-docker",
            "supported-php-projects/apps/linkace-on-docker",
            "supported-php-projects/apps/koel-on-docker",
            "supported-php-projects/apps/azuracast-on-docker",
            "supported-php-projects/apps/lychee-on-docker",
            "supported-php-projects/apps/vanilla-forums-on-docker",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Supported Services",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Databases",
          collapsible: true,
          collapsed: true,
          items: [
            "services/databases/mysql",
            "services/databases/mariadb",
            "services/databases/postgres",
            "services/databases/postgres-postgis",
            "services/databases/mongo",
            "services/databases/mongo-webui",
            "services/databases/rethinkdb",
            "services/databases/cassandra",
            "services/databases/couchdb",
            "services/databases/neo4j",
            "services/databases/mssql",
            "services/databases/percona",
            "services/databases/clickhouse",
            "services/databases/manticore",
            "services/databases/solr",
            "services/databases/ssdb",
            "services/databases/arangodb",
            "services/databases/surrealdb",
            "services/databases/phpmyadmin",
            "services/databases/adminer",
            "services/databases/pgadmin",
            "services/databases/pgbackups",
            "services/databases/pgvector",
          ],
        },
        {
          type: "category",
          label: "Caching & Queues",
          collapsible: true,
          collapsed: true,
          items: [
            "services/caching-queues/redis",
            "services/caching-queues/redis-cluster",
            "services/caching-queues/redis-webui",
            "services/caching-queues/memcached",
            "services/caching-queues/valkey",
            "services/caching-queues/dragonfly",
            "services/caching-queues/aerospike",
            "services/caching-queues/tarantool",
            "services/caching-queues/tarantool-admin",
            "services/caching-queues/kafka",
            "services/caching-queues/kafka-manager",
            "services/caching-queues/beanstalkd",
            "services/caching-queues/beanstalkd-console",
            "services/caching-queues/mosquitto",
            "services/caching-queues/rabbitmq",
            "services/caching-queues/nats",
            "services/caching-queues/zookeeper",
            "services/caching-queues/gearman",
            "services/caching-queues/sqs",
            "services/caching-queues/soketi",
            "services/caching-queues/mercure",
            "services/caching-queues/laravel-echo-server",
            "services/caching-queues/laravel-reverb",
            "services/caching-queues/laravel-horizon",
          ],
        },
        {
          type: "category",
          label: "Search",
          collapsible: true,
          collapsed: true,
          items: [
            "services/search/elasticsearch",
            "services/search/opensearch",
            "services/search/meilisearch",
            "services/search/typesense",
            "services/search/kibana",
            "services/search/dejavu",
          ],
        },
        {
          type: "category",
          label: "AI & ML",
          collapsible: true,
          collapsed: true,
          items: [
            "services/ai-ml/ollama",
            "services/ai-ml/localai",
            "services/ai-ml/litellm",
            "services/ai-ml/n8n",
            "services/ai-ml/flowise",
            "services/ai-ml/qdrant",
            "services/ai-ml/weaviate",
            "services/ai-ml/chroma",
          ],
        },
        {
          type: "category",
          label: "Web Servers & Proxies",
          collapsible: true,
          collapsed: true,
          items: [
            "services/web-servers/nginx",
            "services/web-servers/apache2",
            "services/web-servers/caddy",
            "services/web-servers/openresty",
            "services/web-servers/traefik",
            "services/web-servers/haproxy",
            "services/web-servers/varnish",
            "services/web-servers/frankenphp",
            "services/web-servers/roadrunner",
          ],
        },
        {
          type: "category",
          label: "Mail",
          collapsible: true,
          collapsed: true,
          items: [
            "services/mail/mailpit",
            "services/mail/mailu",
            "services/mail/mailhog",
            "services/mail/maildev",
            "services/mail/mailcatcher",
          ],
        },
        {
          type: "category",
          label: "DevOps & CI/CD",
          collapsible: true,
          collapsed: true,
          items: [
            "services/devops/jenkins",
            "services/devops/gitlab",
            "services/devops/gitlab-runner",
            "services/devops/sonarqube",
            "services/devops/onedev",
            "services/devops/portainer",
            "services/devops/docker-registry",
            "services/devops/docker-in-docker",
            "services/devops/certbot",
            "services/devops/ide-theia",
            "services/devops/swagger-editor",
            "services/devops/swagger-ui",
          ],
        },
        {
          type: "category",
          label: "Monitoring",
          collapsible: true,
          collapsed: true,
          items: [
            "services/monitoring/grafana",
            "services/monitoring/graylog",
            "services/monitoring/netdata",
            "services/monitoring/prometheus",
            "services/monitoring/influxdb",
            "services/monitoring/logstash",
          ],
        },
        {
          type: "category",
          label: "Tools",
          collapsible: true,
          collapsed: true,
          items: [
            "services/tools/keycloak",
            "services/tools/minio",
            "services/tools/thumbor",
            "services/tools/metabase",
            "services/tools/confluence",
            "services/tools/selenium",
            "services/tools/tomcat",
            "services/tools/aws-eb-cli",
            "services/tools/blackfire",
            "services/tools/workspace",
            "services/tools/php-fpm",
            "services/tools/php-worker",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: true,
      items: [
        "containers",
        "environment",
        "networking",
        "production",
        "maintenance",
      ],
    },
    {
      type: "category",
      label: "Laradock vs Others",
      link: { type: "doc", id: "laradock-vs-others/comparison" },
      collapsible: true,
      collapsed: true,
      items: [
        "laradock-vs-others/laradock-vs-ddev",
        "laradock-vs-others/laradock-vs-laravel-sail",
        "laradock-vs-others/laradock-vs-laravel-herd",
        "laradock-vs-others/laradock-vs-valet",
        "laradock-vs-others/laradock-vs-xampp",
        "laradock-vs-others/laradock-vs-laragon",
        "laradock-vs-others/laradock-vs-local-wp",
        "laradock-vs-others/laradock-vs-homestead",
        "laradock-vs-others/laradock-vs-lando",
        "laradock-vs-others/laradock-vs-devcontainers",
        "laradock-vs-others/laradock-vs-docker-compose",
        "laradock-vs-others/laradock-vs-manual-install",
      ],
    },
    "help",
    "community",
    "related-projects",
    "contributing",
  ],
};

export default sidebars;
