services:

    meilisearch:
      image: getmeili/meilisearch:latest
      volumes:
        - ${DATA_PATH_HOST}/meilisearch:/data.ms
      ports:
        - "${MEILISEARCH_HOST_PORT}:7700"
      environment:
        - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
      networks:
        - frontend
        - backend
