services:

    dejavu:
      restart: always
      build:
        context: ./dejavu
      ports:
        - "${DEJAVU_HTTP_PORT}:1358"
      depends_on:
        - elasticsearch
      networks:
        - frontend
        - backend
